#!/usr/bin/env python3
"""
codemap — zero-dependency code map generator.

Builds a dependency graph of a Python + TypeScript project and emits:
  - repomap.md   : a compact, ranked, LLM-friendly map (read one file instead of forty)
  - graph.json   : full structured data (nodes, edges, symbols, routes, ranks)
  - graph.mmd    : a Mermaid diagram (renders in Markdown/GitHub, no graphviz needed)
  - graph.dot    : Graphviz source (+ graph.svg if `dot` is installed)

Python is parsed with the stdlib `ast` module (exact). TypeScript/TSX is parsed
with lightweight regexes (heuristic, good enough for a navigation map).

Usage:
  python tools/codemap/codemap.py                       # full run -> tools/codemap/out/
  python tools/codemap/codemap.py --focus pages.py      # neighborhood of a file -> stdout
  python tools/codemap/codemap.py --format json,mermaid # only some outputs
  python tools/codemap/codemap.py --root . --out build/codemap

Requires only the Python standard library (3.8+).
"""

from __future__ import annotations

import argparse
import ast
import json
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

# --------------------------------------------------------------------------- #
# Config
# --------------------------------------------------------------------------- #

DEFAULT_EXCLUDE_DIRS = {
    ".git", ".hg", ".svn", "node_modules", "__pycache__", "site-packages",
    "venv", ".venv", "env", ".ev", ".tox", ".pytest_cache", ".mypy_cache",
    "build", "dist", "out", "backups", "Design", ".next", "coverage",
    "alembic",  # DB migrations: noise for code navigation
}
# Path fragments (posix-style) that, if contained, exclude the file.
DEFAULT_EXCLUDE_FRAGMENTS = {
    "alembic/versions/",          # autogenerated migrations: historical noise
    ".dist-info", ".egg-info",
}

PY_EXT = {".py"}
TS_EXT = {".ts", ".tsx"}

# Layer detection by path / filename ------------------------------------------------

def detect_layer(rel: str, lang: str) -> str:
    p = rel.replace("\\", "/")
    name = p.rsplit("/", 1)[-1]
    if lang == "py":
        if "/routers/" in p or p.endswith("/routers.py"):
            return "router"
        if "/services/" in p:
            return "service"
        if "/models/" in p:
            return "model"
        if "/schemas/" in p:
            return "schema"
        if name in ("main.py", "asgi.py", "wsgi.py", "app.py"):
            return "entry"
        if name in ("database.py", "config.py", "settings.py", "deps.py", "db.py"):
            return "infra"
        return "module"
    else:  # ts
        if "/pages/" in p:
            return "page"
        if "/hooks/" in p or name.startswith("use"):
            return "hook"
        if "/components/" in p:
            return "component"
        if "/api/" in p or name in ("client.ts", "api.ts"):
            return "api"
        if "/types" in p or name.startswith("types"):
            return "type"
        if "/styles/" in p or "token" in name:
            return "style"
        if name in ("index.tsx", "index.ts", "App.tsx", "main.tsx"):
            return "entry"
        return "module"


LAYER_ORDER = [
    # backend
    "entry", "router", "service", "schema", "model", "infra", "module",
    # frontend
    "page", "component", "hook", "api", "type", "style",
]

LAYER_LABEL = {
    "entry": "entry", "router": "routers (API)", "service": "services (logic)",
    "schema": "schemas (Pydantic)", "model": "models (ORM)", "infra": "foundation",
    "module": "modules", "page": "pages (screens)", "component": "components",
    "hook": "hooks", "api": "api client", "type": "types", "style": "styles",
}

# --------------------------------------------------------------------------- #
# Data model
# --------------------------------------------------------------------------- #

@dataclass
class Symbol:
    kind: str          # class | func | method | route | component | hook | type | const
    name: str
    sig: str = ""
    line: int = 0
    extra: str = ""    # e.g. base classes, route method


@dataclass
class Node:
    id: str            # path relative to root, posix style
    lang: str          # py | ts
    layer: str
    loc: int
    tokens: int                       # rough token estimate of the source
    symbols: List[Symbol] = field(default_factory=list)
    routes: List[str] = field(default_factory=list)      # "GET /api/pages"
    rels: List[str] = field(default_factory=list)        # ORM relationship targets
    ext: List[str] = field(default_factory=list)         # external top-level deps
    imports: List[str] = field(default_factory=list)     # resolved internal node ids
    is_script: bool = False                              # has `if __name__ == "__main__"`
    # filled later
    fan_in: int = 0
    fan_out: int = 0
    rank: float = 0.0


# --------------------------------------------------------------------------- #
# File discovery
# --------------------------------------------------------------------------- #

def discover(root: Path, exclude_dirs: Set[str], exclude_frags: Set[str]) -> List[Path]:
    files: List[Path] = []
    for dirpath, dirnames, filenames in os.walk(root):
        # prune excluded directories in-place
        dirnames[:] = [d for d in dirnames if d not in exclude_dirs]
        for fn in filenames:
            ext = os.path.splitext(fn)[1]
            if ext not in PY_EXT and ext not in TS_EXT:
                continue
            full = Path(dirpath) / fn
            rel = full.relative_to(root).as_posix()
            if any(frag in rel or frag in fn for frag in exclude_frags):
                continue
            if fn.endswith(".d.ts"):
                continue
            files.append(full)
    return sorted(files)


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return path.read_text(encoding="utf-8", errors="replace")
    except Exception:
        return ""


# --------------------------------------------------------------------------- #
# Python analysis (ast)
# --------------------------------------------------------------------------- #

def py_module_name(path: Path) -> Tuple[str, Path]:
    """Return (dotted module name, source-root dir) for a .py file."""
    stem = path.stem
    pkg_parts: List[str] = []
    cur = path.parent
    while (cur / "__init__.py").exists():
        pkg_parts.append(cur.name)
        parent = cur.parent
        if parent == cur:
            break
        cur = parent
    pkg_parts.reverse()
    if stem == "__init__":
        mod = ".".join(pkg_parts)
    else:
        mod = ".".join(pkg_parts + [stem])
    return mod, cur


def arg_names(a: ast.arguments, drop_self: bool = False) -> str:
    names: List[str] = []
    posonly = getattr(a, "posonlyargs", [])
    for x in list(posonly) + list(a.args):
        names.append(x.arg)
    if a.vararg:
        names.append("*" + a.vararg.arg)
    for x in a.kwonlyargs:
        names.append(x.arg)
    if a.kwarg:
        names.append("**" + a.kwarg.arg)
    if drop_self and names and names[0] in ("self", "cls"):
        names = names[1:]
    return ", ".join(names)


def _str_const(node: ast.AST) -> Optional[str]:
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    return None


def analyze_py(path: Path, rel: str, src: str) -> Tuple[Node, List[Tuple[str, str, List[str], int, bool]]]:
    """
    Returns (Node, raw_import_specs).
    raw_import_specs entries: (kind, module, names, level, is_pkg)
       kind = "import" | "from"
    """
    node = Node(id=rel, lang="py", layer=detect_layer(rel, "py"),
                loc=src.count("\n") + 1, tokens=max(1, len(src) // 4))
    raw_imports: List[Tuple[str, str, List[str], int, bool]] = []
    is_pkg = path.stem == "__init__"
    node.is_script = '__name__' in src and '__main__' in src

    try:
        tree = ast.parse(src, filename=str(path))
    except SyntaxError:
        return node, raw_imports

    ext_roots: Set[str] = set()

    # First pass: find APIRouter / app prefixes for route resolution
    router_prefix: Dict[str, str] = {}
    for stmt in tree.body:
        if isinstance(stmt, ast.Assign) and isinstance(stmt.value, ast.Call):
            fn = stmt.value.func
            fn_name = fn.id if isinstance(fn, ast.Name) else (fn.attr if isinstance(fn, ast.Attribute) else "")
            if fn_name in ("APIRouter", "FastAPI"):
                prefix = ""
                for kw in stmt.value.keywords:
                    if kw.arg == "prefix":
                        prefix = _str_const(kw.value) or ""
                for tgt in stmt.targets:
                    if isinstance(tgt, ast.Name):
                        router_prefix[tgt.id] = prefix

    def route_from_decorator(dec: ast.AST) -> Optional[str]:
        if not isinstance(dec, ast.Call):
            return None
        f = dec.func
        if not isinstance(f, ast.Attribute):
            return None
        if not isinstance(f.value, ast.Name):
            return None
        method = f.attr.upper()
        if method not in ("GET", "POST", "PUT", "DELETE", "PATCH", "HEAD", "OPTIONS"):
            return None
        var = f.value.id
        if var not in router_prefix:
            return None
        path_arg = ""
        if dec.args:
            path_arg = _str_const(dec.args[0]) or ""
        full = (router_prefix[var] + path_arg) or "/"
        return f"{method} {full}"

    # Imports + top-level symbols
    for stmt in tree.body:
        if isinstance(stmt, ast.Import):
            mods = [a.name for a in stmt.names]
            for m in mods:
                ext_roots.add(m.split(".")[0])
            raw_imports.append(("import", "", mods, 0, is_pkg))

        elif isinstance(stmt, ast.ImportFrom):
            mod = stmt.module or ""
            names = [a.name for a in stmt.names]
            if stmt.level == 0 and mod:
                ext_roots.add(mod.split(".")[0])
            raw_imports.append(("from", mod, names, stmt.level, is_pkg))

        elif isinstance(stmt, (ast.FunctionDef, ast.AsyncFunctionDef)):
            sig = f"{stmt.name}({arg_names(stmt.args)})"
            node.symbols.append(Symbol("func", stmt.name, sig, stmt.lineno))
            for dec in stmt.decorator_list:
                r = route_from_decorator(dec)
                if r:
                    node.routes.append(r)

        elif isinstance(stmt, ast.ClassDef):
            bases = []
            for b in stmt.bases:
                try:
                    bases.append(ast.unparse(b))
                except Exception:
                    pass
            sym = Symbol("class", stmt.name, "", stmt.lineno, extra=", ".join(bases))
            node.symbols.append(sym)
            # methods + ORM relationships inside the class body
            for sub in stmt.body:
                if isinstance(sub, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    if sub.name.startswith("__"):
                        continue
                    msig = f"{sub.name}({arg_names(sub.args, drop_self=True)})"
                    node.symbols.append(Symbol("method", f"{stmt.name}.{sub.name}", msig, sub.lineno))
                # relationship("Target") assignments
                val = None
                if isinstance(sub, ast.Assign):
                    val = sub.value
                elif isinstance(sub, ast.AnnAssign):
                    val = sub.value
                if isinstance(val, ast.Call):
                    fn = val.func
                    fn_name = fn.id if isinstance(fn, ast.Name) else (fn.attr if isinstance(fn, ast.Attribute) else "")
                    if fn_name == "relationship" and val.args:
                        tgt = _str_const(val.args[0])
                        if tgt:
                            node.rels.append(tgt)

    node.ext = sorted(r for r in ext_roots if r and not r.startswith("_"))
    return node, raw_imports


# --------------------------------------------------------------------------- #
# TypeScript analysis (regex, heuristic)
# --------------------------------------------------------------------------- #

RE_IMPORT_FROM = re.compile(r"""(?:import|export)\b[\s\S]*?from\s*['"]([^'"]+)['"]""")
RE_IMPORT_BARE = re.compile(r"""^\s*import\s*['"]([^'"]+)['"]""", re.M)
RE_EXP_FUNC = re.compile(r"""export\s+(?:default\s+)?(?:async\s+)?function\s+(\w+)\s*\(([^)]*)\)""")
RE_EXP_CLASS = re.compile(r"""export\s+(?:default\s+)?(?:abstract\s+)?class\s+(\w+)""")
RE_EXP_CONST = re.compile(r"""export\s+const\s+(\w+)""")
RE_EXP_TYPE = re.compile(r"""export\s+(?:default\s+)?(?:interface|type)\s+(\w+)""")
RE_EXP_DEFAULT = re.compile(r"""export\s+default\s+(\w+)\s*;""")


def analyze_ts(path: Path, rel: str, src: str) -> Tuple[Node, List[str]]:
    node = Node(id=rel, lang="ts", layer=detect_layer(rel, "ts"),
                loc=src.count("\n") + 1, tokens=max(1, len(src) // 4))
    is_tsx = path.suffix == ".tsx"

    raw_specs: List[str] = []
    ext_roots: Set[str] = set()
    for m in RE_IMPORT_FROM.finditer(src):
        spec = m.group(1)
        raw_specs.append(spec)
        if not spec.startswith(".") and not spec.startswith("@/"):
            ext_roots.add(spec.split("/")[0] if not spec.startswith("@") else spec.split("/")[0])
    for m in RE_IMPORT_BARE.finditer(src):
        raw_specs.append(m.group(1))

    def add(kind: str, name: str, sig: str = ""):
        node.symbols.append(Symbol(kind, name, sig))

    for m in RE_EXP_FUNC.finditer(src):
        name, params = m.group(1), m.group(2)
        clean = ", ".join(p.split(":")[0].strip() for p in params.split(",") if p.strip())
        if name.startswith("use") and len(name) > 3 and name[3].isupper():
            add("hook", name, f"{name}({clean})")
        else:
            add("func", name, f"{name}({clean})")
    for m in RE_EXP_CLASS.finditer(src):
        add("class", m.group(1))
    for m in RE_EXP_CONST.finditer(src):
        name = m.group(1)
        if name.startswith("use") and len(name) > 3 and name[3].isupper():
            add("hook", name)
        elif is_tsx and name[:1].isupper():
            add("component", name)
        else:
            add("const", name)
    for m in RE_EXP_TYPE.finditer(src):
        add("type", m.group(1))

    node.ext = sorted(r for r in ext_roots if r)
    return node, raw_specs


# --------------------------------------------------------------------------- #
# Graph construction (import resolution)
# --------------------------------------------------------------------------- #

def resolve_py_imports(specs, current_mod: str, mod_to_id: Dict[str, str]) -> Set[str]:
    out: Set[str] = set()
    for kind, mod, names, level, is_pkg in specs:
        if kind == "import":
            for m in names:
                if m in mod_to_id:
                    out.add(mod_to_id[m])
            continue
        # from ... import ...
        if level == 0:
            base = mod
        else:
            parts = current_mod.split(".") if current_mod else []
            if not is_pkg and parts:
                parts = parts[:-1]            # package of the current module
            up = level - 1
            if up > 0:
                parts = parts[:-up] if up <= len(parts) else []
            base = ".".join(parts)
            if mod:
                base = base + "." + mod if base else mod
        if base in mod_to_id:
            out.add(mod_to_id[base])
        for n in names:
            full = base + "." + n if base else n
            if full in mod_to_id:
                out.add(mod_to_id[full])
    return out


def resolve_ts_imports(specs, importer: Path, root: Path, ts_ids: Set[str],
                       src_roots: List[Path]) -> Set[str]:
    out: Set[str] = set()
    cand_exts = ["", ".ts", ".tsx", ".d.ts"]
    cand_index = ["/index.ts", "/index.tsx"]
    for spec in specs:
        bases: List[Path] = []
        if spec.startswith("."):
            bases.append((importer.parent / spec))
        elif spec.startswith("@/"):
            for sr in src_roots:
                bases.append(sr / spec[2:])
        else:
            continue
        resolved = None
        for base in bases:
            base = Path(os.path.normpath(str(base)))
            tries = [str(base) + e for e in cand_exts] + [str(base) + e for e in cand_index]
            for t in tries:
                tp = Path(t)
                try:
                    rid = tp.relative_to(root).as_posix()
                except ValueError:
                    continue
                if rid in ts_ids:
                    resolved = rid
                    break
            if resolved:
                break
        if resolved:
            out.add(resolved)
    return out


def pagerank(node_ids: List[str], edges: List[Tuple[str, str]],
             d: float = 0.85, iters: int = 50) -> Dict[str, float]:
    n = len(node_ids)
    if n == 0:
        return {}
    pr = {i: 1.0 / n for i in node_ids}
    incoming: Dict[str, List[str]] = {i: [] for i in node_ids}
    outdeg: Dict[str, int] = {i: 0 for i in node_ids}
    for a, b in edges:
        if a in outdeg and b in incoming:
            outdeg[a] += 1
            incoming[b].append(a)
    for _ in range(iters):
        dangling = sum(pr[i] for i in node_ids if outdeg[i] == 0)
        new = {}
        for i in node_ids:
            s = sum(pr[a] / outdeg[a] for a in incoming[i] if outdeg[a])
            new[i] = (1 - d) / n + d * (s + dangling / n)
        pr = new
    return pr


# --------------------------------------------------------------------------- #
# Build the full model
# --------------------------------------------------------------------------- #

class CodeMap:
    def __init__(self, root: Path):
        self.root = root
        self.nodes: Dict[str, Node] = {}
        self.edges: List[Tuple[str, str]] = []       # importer -> imported
        self.edge_set: Set[Tuple[str, str]] = set()

    def build(self, files: List[Path]):
        py_specs: Dict[str, list] = {}
        ts_specs: Dict[str, list] = {}
        mod_to_id: Dict[str, str] = {}
        py_paths: Dict[str, Tuple[Path, str]] = {}     # id -> (path, module)
        ts_ids: Set[str] = set()
        src_roots: Set[Path] = set()

        for path in files:
            rel = path.relative_to(self.root).as_posix()
            src = read_text(path)
            if path.suffix in PY_EXT:
                node, specs = analyze_py(path, rel, src)
                mod, _root = py_module_name(path)
                self.nodes[rel] = node
                py_specs[rel] = specs
                py_paths[rel] = (path, mod)
                if mod:
                    mod_to_id[mod] = rel
            else:
                node, specs = analyze_ts(path, rel, src)
                self.nodes[rel] = node
                ts_specs[rel] = specs
                ts_ids.add(rel)
                # collect ts source roots (dir named 'src')
                for parent in path.parents:
                    if parent.name == "src" and parent != self.root:
                        src_roots.add(parent)
                        break

        # drop internal top-level packages (e.g. "app") from external-deps lists
        internal_tops = {m.split(".")[0] for m in mod_to_id if m}
        for n in self.nodes.values():
            if n.lang == "py" and internal_tops:
                n.ext = [e for e in n.ext if e not in internal_tops]

        # resolve python edges
        for rel, specs in py_specs.items():
            _path, mod = py_paths[rel]
            for tgt in resolve_py_imports(specs, mod, mod_to_id):
                self._add_edge(rel, tgt)

        # resolve typescript edges
        src_root_list = sorted(src_roots, key=lambda p: -len(str(p)))
        for rel, specs in ts_specs.items():
            importer = self.root / rel
            for tgt in resolve_ts_imports(specs, importer, self.root, ts_ids, src_root_list):
                self._add_edge(rel, tgt)

        # conceptual HTTP boundary: ts api client -> backend entry
        self._wire_http_boundary()

        # drop empty package __init__ files (pure noise for navigation)
        trivial = {nid for nid, n in self.nodes.items()
                   if nid.rsplit("/", 1)[-1] == "__init__.py" and n.loc <= 2 and not n.symbols}
        if trivial:
            for t in trivial:
                del self.nodes[t]
            self.edges = [(a, b) for (a, b) in self.edges if a not in trivial and b not in trivial]
            self.edge_set = set(self.edges)

        # degrees + rank
        for a, b in self.edges:
            self.nodes[a].fan_out += 1
            self.nodes[b].fan_in += 1
        ranks = pagerank(list(self.nodes.keys()),
                         [(a, b) for (a, b) in self.edges])
        for nid, r in ranks.items():
            self.nodes[nid].rank = r
        # store imports list per node (resolved)
        for a, b in self.edges:
            self.nodes[a].imports.append(b)

    def _add_edge(self, a: str, b: str):
        if a == b:
            return
        key = (a, b)
        if key in self.edge_set:
            return
        self.edge_set.add(key)
        self.edges.append(key)

    def _wire_http_boundary(self):
        api_nodes = [n for n in self.nodes.values() if n.lang == "ts" and n.layer == "api"]
        entry_be = [n for n in self.nodes.values() if n.lang == "py" and n.layer == "entry"]
        for a in api_nodes:
            for e in entry_be:
                self._add_edge(a.id, e.id)

    # ---- derived facts ------------------------------------------------------
    def orphans(self) -> List[Node]:
        """Files never imported by anything else — dead code candidates.
        Excludes entrypoints, package __init__ files and standalone scripts."""
        out = []
        for n in self.nodes.values():
            if n.fan_in != 0:
                continue
            if n.layer == "entry" or n.is_script:
                continue
            if n.id.rsplit("/", 1)[-1] == "__init__.py":
                continue
            out.append(n)
        return out

    def hotspots(self, top: int = 6) -> List[Node]:
        ranked = sorted(self.nodes.values(), key=lambda n: (-n.fan_in, -n.loc))
        return [n for n in ranked if n.fan_in >= 3][:top]

    def stats(self) -> dict:
        total_loc = sum(n.loc for n in self.nodes.values())
        total_tokens = sum(n.tokens for n in self.nodes.values())
        return {
            "files": len(self.nodes),
            "py_files": sum(1 for n in self.nodes.values() if n.lang == "py"),
            "ts_files": sum(1 for n in self.nodes.values() if n.lang == "ts"),
            "edges": len(self.edges),
            "loc": total_loc,
            "source_tokens_est": total_tokens,
        }


# --------------------------------------------------------------------------- #
# Renderers
# --------------------------------------------------------------------------- #

def _grouped(nodes: List[Node]) -> List[Tuple[str, str, List[Node]]]:
    """Group nodes by (lang, layer) in a sensible reading order."""
    out = []
    for lang, lang_label in (("py", "Backend · Python"), ("ts", "Frontend · TypeScript")):
        for layer in LAYER_ORDER:
            group = [n for n in nodes if n.lang == lang and n.layer == layer]
            if group:
                group.sort(key=lambda n: (-n.rank, -n.loc, n.id))
                out.append((lang_label, LAYER_LABEL.get(layer, layer), group))
    return out


def render_repomap(cm: CodeMap, max_symbols: int = 8) -> str:
    st = cm.stats()
    map_tokens = "?"
    lines: List[str] = []
    A = lines.append
    A(f"# Repo map — {cm.root.name}")
    A("")
    A(f"_{st['files']} files · {st['py_files']} py + {st['ts_files']} ts · "
      f"{st['loc']:,} LOC · {st['edges']} import edges._")
    A(f"_Reading the full source ≈ **{st['source_tokens_est']:,} tokens**. "
      f"This map ≈ **{{MAP_TOKENS}} tokens** — read it first to orient._")
    A("")
    A("**How to read** — files grouped by layer, ordered by importance (PageRank). "
      "`↓N` = used by N files (fan-in), `↑N` = imports N files (fan-out), `★` = rank. "
      "Start at the top of each group: those are the load-bearing files.")
    A("")

    # hotspots / orphans up top
    hs = cm.hotspots()
    if hs:
        A("## ⚠ Hotspots (touch with care — many files depend on them)")
        for n in hs:
            A(f"- `{n.id}` — ↓{n.fan_in} dependents, {n.loc} loc")
        A("")
    orph = cm.orphans()
    if orph:
        A("## ⚠ Never imported (dead-code candidates — verify before relying on them)")
        for n in sorted(orph, key=lambda n: -n.loc):
            A(f"- `{n.id}` — {n.loc} loc")
        A("")

    for lang_label, layer_label, group in _grouped(list(cm.nodes.values())):
        A(f"## {lang_label} · {layer_label}")
        for n in group:
            star = f"★{n.rank:.3f}"
            A(f"### `{n.id}` · {n.loc} loc · ↓{n.fan_in} ↑{n.fan_out} · {star}")
            if n.ext:
                A(f"- ext: {', '.join(n.ext[:8])}")
            if n.imports:
                imps = ", ".join(sorted(cm.nodes[i].id for i in n.imports))
                A(f"- imports: {imps}")
            used_by = sorted(a for (a, b) in cm.edges if b == n.id)
            if used_by:
                A(f"- used-by: {', '.join(used_by)}")
            if n.routes:
                A(f"- routes: {', '.join(n.routes)}")
            if n.rels:
                A(f"- model→model: {', '.join(sorted(set(n.rels)))}")
            if n.symbols:
                shown = n.symbols[:max_symbols]
                defs = ", ".join(s.sig or s.name for s in shown)
                more = "" if len(n.symbols) <= max_symbols else f" (+{len(n.symbols) - max_symbols} more)"
                A(f"- defs: {defs}{more}")
            A("")
    text = "\n".join(lines)
    # estimate own size and patch the placeholder
    est = max(1, len(text) // 4)
    return text.replace("{MAP_TOKENS}", f"{est:,}")


def render_json(cm: CodeMap) -> str:
    payload = {
        "root": cm.root.name,
        "stats": cm.stats(),
        "hotspots": [n.id for n in cm.hotspots()],
        "orphans": [n.id for n in cm.orphans()],
        "nodes": [
            {
                "id": n.id, "lang": n.lang, "layer": n.layer, "loc": n.loc,
                "tokens": n.tokens, "rank": round(n.rank, 5),
                "fan_in": n.fan_in, "fan_out": n.fan_out,
                "imports": sorted(n.imports), "ext": n.ext,
                "routes": n.routes, "rels": sorted(set(n.rels)),
                "symbols": [asdict(s) for s in n.symbols],
            }
            for n in sorted(cm.nodes.values(), key=lambda n: (-n.rank, n.id))
        ],
        "edges": [{"from": a, "to": b} for (a, b) in cm.edges],
    }
    return json.dumps(payload, ensure_ascii=False, indent=2)


MERMAID_CLASSDEF = {
    "router": "fill:#1d2c45,stroke:#5b9dff,color:#dce8ff",
    "service": "fill:#2a2140,stroke:#a880ff,color:#ece3ff",
    "model": "fill:#3a2f12,stroke:#f2b23d,color:#ffedc2",
    "schema": "fill:#10322c,stroke:#34c0aa,color:#cdf3ec",
    "infra": "fill:#23272f,stroke:#828c9e,color:#dfe4ec",
    "entry": "fill:#2b1518,stroke:#ff7088,color:#ffd9df",
    "page": "fill:#1d2c45,stroke:#5b9dff,color:#dce8ff",
    "component": "fill:#23272f,stroke:#828c9e,color:#dfe4ec",
    "hook": "fill:#3a2f12,stroke:#f2b23d,color:#ffedc2",
    "api": "fill:#10322c,stroke:#34c0aa,color:#cdf3ec",
    "type": "fill:#23272f,stroke:#6f7889,color:#cfd5df",
    "style": "fill:#23272f,stroke:#6f7889,color:#cfd5df",
    "module": "fill:#23272f,stroke:#6f7889,color:#cfd5df",
}


def _mid(nid: str) -> str:
    return "n_" + re.sub(r"[^0-9a-zA-Z]", "_", nid)


def render_mermaid(cm: CodeMap, nodes: Optional[List[Node]] = None) -> str:
    nodes = nodes or list(cm.nodes.values())
    ids = {n.id for n in nodes}
    lines = ["flowchart LR"]
    used_layers: Set[str] = set()
    # group into subgraphs by lang+layer
    for lang, lang_label in (("py", "Backend"), ("ts", "Frontend")):
        lang_nodes = [n for n in nodes if n.lang == lang]
        if not lang_nodes:
            continue
        lines.append(f"  subgraph {lang_label}")
        lines.append("    direction TB")
        for layer in LAYER_ORDER:
            grp = [n for n in lang_nodes if n.layer == layer]
            if not grp:
                continue
            sgid = f"{lang}_{layer}"
            lines.append(f'    subgraph {sgid}["{LAYER_LABEL.get(layer, layer)}"]')
            for n in sorted(grp, key=lambda n: -n.rank):
                label = n.id.rsplit("/", 1)[-1]
                lines.append(f'      {_mid(n.id)}["{label}<br/>{n.loc} loc"]')
                used_layers.add(layer)
            lines.append("    end")
        lines.append("  end")
    # edges
    for a, b in cm.edges:
        if a in ids and b in ids:
            lines.append(f"  {_mid(a)} --> {_mid(b)}")
    # styling
    for layer in used_layers:
        cls = MERMAID_CLASSDEF.get(layer)
        if cls:
            lines.append(f"  classDef {layer} {cls};")
    for n in nodes:
        if n.layer in used_layers and n.layer in MERMAID_CLASSDEF:
            lines.append(f"  class {_mid(n.id)} {n.layer};")
    return "\n".join(lines)


def render_dot(cm: CodeMap, nodes: Optional[List[Node]] = None) -> str:
    nodes = nodes or list(cm.nodes.values())
    ids = {n.id for n in nodes}
    color = {
        "router": "#5b9dff", "service": "#a880ff", "model": "#f2b23d",
        "schema": "#34c0aa", "infra": "#828c9e", "entry": "#ff7088",
        "page": "#5b9dff", "component": "#828c9e", "hook": "#f2b23d",
        "api": "#34c0aa", "type": "#6f7889", "style": "#6f7889", "module": "#9aa3b2",
    }
    lines = ['digraph codemap {', '  rankdir=LR;', '  bgcolor="#0e1118";',
             '  node [shape=box style="rounded,filled" fontname="Helvetica" '
             'fontsize=10 color="#2a313f" fontcolor="#e7eaf0"];',
             '  edge [color="#3a4252" arrowsize=0.6];']
    for n in sorted(nodes, key=lambda n: n.id):
        fill = color.get(n.layer, "#23272f")
        label = n.id.rsplit("/", 1)[-1].replace('"', '')
        lines.append(f'  "{n.id}" [label="{label}\\n{n.loc} loc" '
                     f'fillcolor="{fill}22" color="{fill}"];')
    for a, b in cm.edges:
        if a in ids and b in ids:
            lines.append(f'  "{a}" -> "{b}";')
    lines.append("}")
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# Focus mode (neighborhood of a file)
# --------------------------------------------------------------------------- #

def focus(cm: CodeMap, query: str, depth: int = 1) -> str:
    matches = [n for n in cm.nodes.values() if query in n.id]
    if not matches:
        return f"No file matches '{query}'. Try a path fragment like 'pages.py' or 'DiffView'."
    seed = sorted(matches, key=lambda n: (-n.rank, n.id))[0]
    keep: Set[str] = {seed.id}
    frontier = {seed.id}
    for _ in range(depth):
        nxt: Set[str] = set()
        for nid in frontier:
            for a, b in cm.edges:
                if a == nid:
                    nxt.add(b)
                if b == nid:
                    nxt.add(a)
        nxt -= keep
        keep |= nxt
        frontier = nxt

    lines: List[str] = []
    A = lines.append
    A(f"# Focus: {seed.id}")
    A(f"_neighborhood, depth {depth} · {len(keep)} files_")
    A("")
    deps = sorted(b for (a, b) in cm.edges if a == seed.id)
    used = sorted(a for (a, b) in cm.edges if b == seed.id)
    A(f"**{seed.id}** · {seed.loc} loc · {seed.layer}")
    if seed.routes:
        A(f"- routes: {', '.join(seed.routes)}")
    if seed.symbols:
        A(f"- defs: {', '.join(s.sig or s.name for s in seed.symbols[:12])}")
    A(f"- imports ({len(deps)}): {', '.join(deps) or '—'}")
    A(f"- used-by ({len(used)}): {', '.join(used) or '—'}")
    A("")
    A("## Neighborhood")
    sub = [cm.nodes[i] for i in keep]
    for lang_label, layer_label, group in _grouped(sub):
        for n in group:
            mark = " ← FOCUS" if n.id == seed.id else ""
            A(f"- `{n.id}` · {n.layer} · {n.loc} loc · ↓{n.fan_in} ↑{n.fan_out}{mark}")
    A("")
    A("## Mermaid")
    A("```mermaid")
    sub_cm = CodeMap(cm.root)
    sub_cm.nodes = {i: cm.nodes[i] for i in keep}
    sub_cm.edges = [(a, b) for (a, b) in cm.edges if a in keep and b in keep]
    A(render_mermaid(sub_cm, sub))
    A("```")
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #

def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Generate a code map (dependency graph + LLM repo map).")
    here = Path(__file__).resolve()
    default_root = here.parents[2] if len(here.parents) >= 3 else Path.cwd()
    parser.add_argument("--root", default=str(default_root),
                        help="project root to scan (default: repo root)")
    parser.add_argument("--out", default=str(here.parent / "out"),
                        help="output directory")
    parser.add_argument("--format", default="md,json,mermaid,dot",
                        help="comma list: md,json,mermaid,dot")
    parser.add_argument("--focus", default=None,
                        help="print the neighborhood of a file (by path fragment) to stdout")
    parser.add_argument("--depth", type=int, default=1, help="focus depth (default 1)")
    parser.add_argument("--exclude", default="",
                        help="extra comma-separated directory names to exclude")
    args = parser.parse_args(argv)

    root = Path(args.root).resolve()
    if not root.exists():
        print(f"error: root does not exist: {root}", file=sys.stderr)
        return 2

    exclude_dirs = set(DEFAULT_EXCLUDE_DIRS)
    exclude_dirs.update(d.strip() for d in args.exclude.split(",") if d.strip())

    files = discover(root, exclude_dirs, DEFAULT_EXCLUDE_FRAGMENTS)
    cm = CodeMap(root)
    cm.build(files)

    if args.focus:
        print(focus(cm, args.focus, args.depth))
        return 0

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    fmts = {f.strip() for f in args.format.split(",") if f.strip()}
    written: List[str] = []

    if "md" in fmts:
        (out / "repomap.md").write_text(render_repomap(cm), encoding="utf-8")
        written.append("repomap.md")
    if "json" in fmts:
        (out / "graph.json").write_text(render_json(cm), encoding="utf-8")
        written.append("graph.json")
    if "mermaid" in fmts:
        (out / "graph.mmd").write_text(render_mermaid(cm), encoding="utf-8")
        written.append("graph.mmd")
    if "dot" in fmts:
        dot_src = render_dot(cm)
        (out / "graph.dot").write_text(dot_src, encoding="utf-8")
        written.append("graph.dot")
        dot_bin = shutil.which("dot")
        if dot_bin:
            try:
                subprocess.run([dot_bin, "-Tsvg", str(out / "graph.dot"),
                                "-o", str(out / "graph.svg")], check=True,
                               capture_output=True, timeout=60)
                written.append("graph.svg")
            except Exception as e:
                print(f"note: graphviz present but render failed: {e}", file=sys.stderr)

    st = cm.stats()
    print(f"codemap: {st['files']} files, {st['edges']} edges, {st['loc']:,} LOC")
    print(f"  source ≈ {st['source_tokens_est']:,} tokens")
    print(f"  hotspots: {', '.join(n.id for n in cm.hotspots()) or '—'}")
    orph = cm.orphans()
    if orph:
        print(f"  unreferenced: {', '.join(n.id for n in orph)}")
    print(f"  wrote {len(written)} file(s) to {out}: {', '.join(written)}")
    if "dot" in fmts and not shutil.which("dot"):
        print("  (install graphviz for graph.svg: `brew install graphviz`)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
